import Head from 'next/head'
export default function Header(){

    return <div className="Header">
                <Head>
                  <title>My first basic NextJs App</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
            <h1>This is header component</h1>
    </div>
}