import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import Header from "./components/Header";
import Footer from "./components/Footer";

export default function Home() {
  
  return <>
          <Header/>
              <div className={styles.container}>
                <Head>
                  <title>My first basic NextJs App</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1>Welcome to NextJs !</h1>
                
                    <Link href="/test/test">Click me</Link>
                </main>
              </div>
              <Footer/>
        </>
}
